FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD magicbus.jar /opt/magicbus/
EXPOSE 8080
WORKDIR /opt/magicbus/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "magicbus.jar"]
